baseURL = "https://aryamanz29.github.io/posts"
languageCode = "en-us"
title = "Aryaman's blog"
theme = "github-style"
#googleAnalytics = "UA-123456-789"
#pygmentsCodeFences = true
#pygmentsUseClasses = true

[params]
  author = "Aryaman"
  description = "Blogs by Aryamanz29 ğŸ‘¨â€ğŸ’», Built with Github Actions ğŸš€"
  github = "Aryamanz29"
  #facebook = ""
  twitter = "AryamanZ29"
  linkedin = "aryamanz29"
  instagram = "aryaman_z29"
  #tumblr = ""
  email = "aryamanz29@gmail.com"
  url = "https://aryamanz29.github.io/"
  #keywords = "blog, google analytics"
  #rss = true
  lastmod = true
  userStatusEmoji = "ğŸŒ "
  favicon = "/posts/images/github.png"
  location = "India"
  
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
