name: gh-serve

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tunneling ğŸ› 
        uses: oscarnevarezleal/ngrok-tunneling-action@dev
        id: tunnel
        with:
          port: 1313
          ngrok_authtoken: ${{ secrets.NGROK_TOKEN }}
          timeout: 5m

      - name: Setup Hugo ğŸ‘¨â€ğŸ’»
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - uses: actions/checkout@v2

      - name: Run Hugo ğŸš€
        run : |
          git clone https://github.com/MeiK2333/github-style.git themes/github-style
          hugo serve -D -b ${{ steps.tunnel.outputs.public-url }} --appendPort=false --liveReloadPort=443 --navigateToChanged -t github-style --port 1313 &

      - run: echo "Navigate to ${{ steps.tunnel.outputs.public-url }}"
      - run: |
          echo "âš¡ Listening"
          sleep 5m