name: remove-issue-posts ğŸ§¹

on:
  issues:
    types:
      - closed

jobs:
  remove-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Remove content ğŸ§¹
        run : |
          file="content/post/${{ github.event.issue.title }}.md"
          file=$(echo $file | tr -d ' ')
          echo "Post Name : $file"
          echo "Deleting $file ğŸ§¹"
          rm -rf $file

      - name: Publish content ğŸš€
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: 'Removed post: ${{ github.event.issue.title }}'
          commit_options: '--allow-empty'
          repository: .
          status_options: '--untracked-files=no'
          file_pattern: 'content/**/*'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          disable_globbing: true

      # checkout to the commit that has been pushed
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      # install Hugo
      - name: Setup Hugo ğŸ› 
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          extended: true

      # build website
      - name: Build ğŸ‘¨â€ğŸ’»
        run: hugo --minify

      # push the generated content into the `main` (former `master`) branch.
      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # if your main branch is `master` use that here.
          publish_dir: ./public

