name: remove-issue-posts ðŸ§¹

on:
  issues:
    types:
      - closed

jobs:
  remove-post:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo ðŸ› 
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - uses: actions/checkout@v2

      - name: Remove content ðŸ§¹
        run : |
          mkdir -p content/posts
          git clone https://github.com/spf13/hyde.git themes/hyde
          file="content/posts/${{ github.event.issue.title }}.md"
          file=$(echo $file | tr -d ' ')
          echo "Post Name : $file"
          echo "Deleting $file ðŸ§¹"
          rm -rf $file
          hugo -D -b https://aryamanz29.github.io/posts/ -t hyde

      - name: Publish content ðŸš€
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: 'Removed post: ${{ github.event.issue.title }}'
          commit_options: '--allow-empty'
          repository: .
          status_options: '--untracked-files=no'
          file_pattern: 'content/**/*'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
          disable_globbing: true

      - name: Update Gh-pages âœ…
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public